# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostSyndicateAtmosTech
  name: job-name-typan-atmos-tech
  playTimeTracker: JobOutpostTypanAtmosTech
  salary: 45000 #Lua 35000<45000
  description: Взлом, постройка баррикад, обслуживание шаттлов и Нордфолла - ваша работа.
  startingGear: SyndicateAtmos
  icon: "JobIconSyndicateAtmos"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  hideConsoleVisibility: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Antag
      time: 50000 #Lua 29<50
    - !type:DepartmentTimeRequirement
      department: Security
      time: 150000 #Lua 10<150
    - !type:OverallPlaytimeRequirement
      time: 250000 #Lua 360<250
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate
      - type: SpecialSectorStationRecord
        recordGeneration: FalseRecord
      - type: MailDisabled
      - type: NpcFactionMember
        factions:
        - LuaNordFoll
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNordfoll ]

- type: startingGear
  id: SyndicateAtmos
  equipment:
    ears: ClothingHeadsetAltOutpostSyndicate
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndie
    shoes: ClothingShoesBootsOutpostSyndicate
    back: ClothingBackpackSyndicateFilled
    belt: ClothingBeltAssaultOutpostSyndicate
    id: SyndiPDAEng

- type: chameleonOutfit
  id: OutpostSyndicateAtmosTechChameleonOutfit
  job: OutpostSyndicateAtmosTech
  equipment:
    jumpsuit: ClothingUniformJumpsuitChiefEngineerSyndie
